#!/usr/bin/env bash

write_target_fstab() {
  local root_uuid esp_uuid
  root_uuid=$(blkid -s UUID -o value "/dev/mapper/$CRYPT_NAME")
  esp_uuid=$(blkid -s UUID -o value "$ESP_PART")

  cat > "$INSTALL_ROOT/etc/fstab" <<EOF_FSTAB
# Generated by arch-workstation. See docs/ARCHITECTURE.md.
UUID=$root_uuid  /                       btrfs  rw,noatime,compress=zstd:1,subvol=@           0 0
UUID=$root_uuid  /home                   btrfs  rw,noatime,compress=zstd:1,subvol=@home       0 0
UUID=$root_uuid  /var/log                btrfs  rw,noatime,compress=zstd:1,subvol=@var_log    0 0
UUID=$root_uuid  /var/cache/pacman/pkg   btrfs  rw,noatime,compress=zstd:1,subvol=@pkg        0 0
UUID=$root_uuid  /var/lib/arch-workstation/pending-credentials btrfs rw,noatime,compress=zstd:1,subvol=@credentials 0 0
UUID=$root_uuid  /.snapshots             btrfs  rw,noatime,compress=zstd:1,subvol=@snapshots  0 0
UUID=$esp_uuid   /efi                    vfat   rw,relatime,fmask=0077,dmask=0077,utf8,errors=remount-ro    0 2
EOF_FSTAB
}

copy_repository_to_target() {
  local target="$INSTALL_ROOT/opt/arch-workstation"
  local provenance="source-archive"
  local git_toplevel=""
  mkdir -p "$target"

  # A Git worktree is copied from its tracked-file set. This preserves tracked
  # customisations while excluding .git internals, ignored secrets, and other
  # untracked files from the installed root-owned source snapshot.
  if command -v git >/dev/null 2>&1; then
    git_toplevel=$(git -C "$REPO_ROOT" rev-parse --show-toplevel 2>/dev/null || true)
  fi
  if [[ -n $git_toplevel && $(readlink -f "$git_toplevel") == $(readlink -f "$REPO_ROOT") ]]; then
    provenance=$(git -C "$REPO_ROOT" rev-parse HEAD)
    if ! git -C "$REPO_ROOT" diff --quiet HEAD -- \
      || ! git -C "$REPO_ROOT" diff --cached --quiet HEAD -- \
      || [[ -n $(git -C "$REPO_ROOT" ls-files --others --exclude-standard) ]]; then
      provenance+="-dirty"
    fi
    (
      cd "$REPO_ROOT" || exit 1
      git ls-files -z \
        | tar --create --file=- --null \
          --exclude='config/install.conf' \
          --exclude='config/usb-secrets.json' \
          --exclude='config/secrets.conf' \
          --exclude='config/secrets.env' \
          --exclude='*.secret' \
          --exclude='*.key' \
          --exclude='*.pem' \
          --exclude='*.gpg' \
          --exclude='*.iso' \
          --exclude='*.bundle' \
          --exclude='*.zip' \
          --exclude='*.tar.gz' \
          --exclude='usb/output' \
          --exclude='usb/output/*' \
          --exclude='usb/work' \
          --exclude='usb/work/*' \
          --files-from=-
    ) | tar -C "$target" -xf -
  else
    tar -C "$REPO_ROOT" \
      --exclude='.git' \
      --exclude='config/install.conf' \
      --exclude='config/usb-secrets.json' \
      --exclude='config/secrets.conf' \
      --exclude='config/secrets.env' \
      --exclude='*.secret' \
      --exclude='*.key' \
      --exclude='*.pem' \
      --exclude='*.gpg' \
      --exclude='*.iso' \
      --exclude='*.bundle' \
      --exclude='usb/output' \
      --exclude='usb/work' \
      --exclude='*.zip' \
      --exclude='*.tar.gz' \
      -cf - . | tar -C "$target" -xf -
  fi
  printf '%s\n' "$provenance" > "$target/BUILD_COMMIT"

  install -Dm0644 "$CONFIG_FILE" "$target/config/install.conf"
  chmod 0755 "$target/install.sh" "$target/start.sh" "$target/archctl" \
    "$target/upgrade-existing.sh" "$target/build-usb.sh"
  find "$target/scripts" "$target/usb" -type f -name '*.sh' -exec chmod 0755 {} +
}

enable_live_iso_multilib() {
  if ! bool_true "$ENABLE_MULTILIB"; then
    return 0
  fi

  info "Enabling multilib in the live ISO before package resolution."
  if ! pacman-conf --repo-list 2>/dev/null | grep -qx multilib; then
    local temp_conf
    temp_conf=$(mktemp)
    awk '
      /^#?\[multilib\]$/ {
        print "[multilib]"
        in_multilib = 1
        found_multilib = 1
        next
      }
      in_multilib && /^#?Include[[:space:]]*=[[:space:]]*\/etc\/pacman\.d\/mirrorlist$/ {
        sub(/^#/, "")
        print
        next
      }
      in_multilib && /^\[/ { in_multilib = 0 }
      { print }
      END {
        if (!found_multilib) {
          print ""
          print "[multilib]"
          print "Include = /etc/pacman.d/mirrorlist"
        }
      }
    ' /etc/pacman.conf > "$temp_conf"
    install -m 0644 "$temp_conf" /etc/pacman.conf
    rm -f "$temp_conf"
  fi

  pacman-conf --repo-list | grep -qx multilib \
    || die "Could not enable the multilib repository in the live ISO."
  if [[ ${ARCHWS_SOURCE_MODE:-live} == offline ]]; then
    [[ -e /var/lib/pacman/sync/multilib.db || -e /var/lib/pacman/sync/multilib.db.tar.gz ]] \
      || die "The cached multilib database is unavailable in offline mode."
  else
    pacman -Sy --noconfirm
  fi
  pacman -Slq multilib >/dev/null 2>&1 \
    || die "The multilib repository database is unavailable in the live ISO."
}

build_package_lists() {
  local -a kernels cpu_packages gpu_packages
  read -r -a kernels <<< "$KERNELS"

  case "$CPU_VENDOR" in
    intel) cpu_packages=(intel-ucode sof-firmware) ;;
    amd) cpu_packages=(amd-ucode) ;;
  esac

  case "$GPU_VENDOR" in
    intel) gpu_packages=(mesa vulkan-intel intel-media-driver) ;;
    amd) gpu_packages=(mesa vulkan-radeon libva-mesa-driver) ;;
    generic) gpu_packages=(mesa) ;;
  esac

  BASE_INSTALL_PACKAGES=(
    base base-devel archlinux-keyring "${kernels[@]}" linux-firmware wireless-regdb "${cpu_packages[@]}"
    btrfs-progs cryptsetup dosfstools gptfdisk efibootmgr
    mkinitcpio systemd-ukify sbsigntools sbctl tpm2-tools tpm2-tss
    networkmanager wpa_supplicant openssh
    sudo git vim curl rsync tar ansible-core python
    man-db man-pages texinfo bash-completion
    zram-generator
    xorg-server xorg-xinit xf86-input-libinput "${gpu_packages[@]}"
    xfce4-session xfce4-panel xfdesktop xfwm4 xfce4-settings xfce4-appfinder
    xfce4-terminal xfce4-power-manager xfce4-notifyd xfce4-screensaver
    xfce4-pulseaudio-plugin thunar thunar-volman tumbler
    lightdm lightdm-gtk-greeter
    pipewire pipewire-alsa pipewire-pulse wireplumber pavucontrol
    bluez bluez-utils
    gnome-keyring polkit-gnome
    gvfs gvfs-mtp udisks2 network-manager-applet
    xdg-user-dirs xdg-utils xdg-desktop-portal-gtk
    noto-fonts noto-fonts-emoji ttf-dejavu
  )

  REQUIRED_OFFICIAL_PACKAGES=(
    "${BASE_INSTALL_PACKAGES[@]}"
    bat btop fd fastfetch fzf jq less pacman-contrib ripgrep unzip wget zip
    file-roller mousepad ristretto xdg-desktop-portal
    cmake dotnet-sdk ninja shellcheck
  )

  if bool_true "$ENABLE_DOCKER"; then
    REQUIRED_OFFICIAL_PACKAGES+=(docker docker-buildx docker-compose)
  fi
  if bool_true "$ENABLE_GAMING"; then
    REQUIRED_OFFICIAL_PACKAGES+=(
      steam gamemode lib32-gamemode lib32-libpulse lib32-mesa mangohud vulkan-tools
    )
    case "$GPU_VENDOR" in
      intel) REQUIRED_OFFICIAL_PACKAGES+=(vulkan-intel lib32-vulkan-intel) ;;
      amd) REQUIRED_OFFICIAL_PACKAGES+=(vulkan-radeon lib32-vulkan-radeon) ;;
    esac
  fi
  if bool_true "$ENABLE_SNAPSHOTS"; then
    REQUIRED_OFFICIAL_PACKAGES+=(snapper snap-pac)
  fi
  if bool_true "$ENABLE_T480"; then
    REQUIRED_OFFICIAL_PACKAGES+=(bolt ethtool fwupd smartmontools thermald tlp tlp-rdw)
  fi

  mapfile -t REQUIRED_OFFICIAL_PACKAGES < <(printf '%s\n' "${REQUIRED_OFFICIAL_PACKAGES[@]}" | sort -u)
}

verify_live_package_resolution() {
  build_package_lists
  info "Resolving every configured official package before touching the target disk."
  pacman -Sp --noconfirm --print-format '%n' "${REQUIRED_OFFICIAL_PACKAGES[@]}" >/dev/null \
    || die "One or more required official packages cannot be resolved. Check mirrors and repository configuration."
}

verify_offline_package_payloads() {
  build_package_lists
  local cache_dir=${ARCHWS_PACKAGE_CACHE_DIR:-}
  local sync_dir=${ARCHWS_SYNC_CACHE_DIR:-}
  local db_path url filename transaction_output
  local -a urls=() missing=()

  [[ -n $cache_dir && -d $cache_dir ]] || die 'Offline package cache directory is unavailable.'
  [[ -n $sync_dir && -d $sync_dir ]] || die 'Offline package database directory is unavailable.'
  db_path=$(dirname -- "$sync_dir")

  info 'Verifying that every package in the offline transaction has a cached payload.'
  if ! transaction_output=$(
      pacman --dbpath "$db_path" --cachedir "$cache_dir" \
        -Sp --noconfirm --print-format '%l' "${REQUIRED_OFFICIAL_PACKAGES[@]}"
    ); then
    die 'Could not resolve the complete offline package transaction.'
  fi
  mapfile -t urls <<< "$transaction_output"

  for url in "${urls[@]}"; do
    [[ -n $url ]] || continue
    filename=${url##*/}
    [[ -s $cache_dir/$filename ]] || missing+=("$filename")
  done
  if ((${#missing[@]})); then
    printf 'Missing offline package payloads:\n' >&2
    printf '  %s\n' "${missing[@]}" >&2
    die 'Refresh the USB package cache before attempting an offline installation.'
  fi
  success "Verified ${#urls[@]} cached package payloads for the offline transaction."
}

resolve_offline_base_package_files() {
  local cache_dir=${ARCHWS_PACKAGE_CACHE_DIR:-}
  local sync_dir=${ARCHWS_SYNC_CACHE_DIR:-}
  local db_path transaction_output url filename package_path
  local -a package_paths=()

  [[ -n $cache_dir && -d $cache_dir ]] || die 'Offline package cache directory is unavailable.'
  [[ -n $sync_dir && -d $sync_dir ]] || die 'Offline package database directory is unavailable.'
  db_path=$(dirname -- "$sync_dir")

  transaction_output=$(
    pacman --dbpath "$db_path" --cachedir "$cache_dir" \
      -Sp --noconfirm --print-format '%l' "${BASE_INSTALL_PACKAGES[@]}"
  ) || die 'Could not resolve the offline base-system transaction.'

  while IFS= read -r url; do
    [[ -n $url ]] || continue
    filename=${url##*/}
    package_path="$cache_dir/$filename"
    [[ -s $package_path ]] || die "Offline base package is missing: $filename"
    package_paths+=("$package_path")
  done <<< "$transaction_output"

  ((${#package_paths[@]})) || die 'The offline base-system transaction resolved to no package files.'
  printf '%s\n' "${package_paths[@]}" | sort -u
}

verify_aur_package_resolution() {
  bool_true "$ENABLE_AUR" || return 0
  if [[ ${ARCHWS_SOURCE_MODE:-live} == offline ]]; then
    warn "Skipping live AUR metadata verification in offline mode; AUR applications are completed during first-boot provisioning when online."
    return 0
  fi

  local -a packages curl_args
  local package response
  read -r -a packages <<< "$AUR_PACKAGES"
  packages=("$AUR_HELPER_PACKAGE" "${packages[@]}")
  curl_args=(--fail --silent --show-error --retry 3 --get)
  for package in "${packages[@]}"; do
    curl_args+=(--data-urlencode "arg[]=$package")
  done

  info "Resolving the configured AUR allow-list before touching the target disk."
  response=$(curl "${curl_args[@]}" https://aur.archlinux.org/rpc/v5/info) \
    || die "Could not query AUR package metadata."
  for package in "${packages[@]}"; do
    grep -Eq '"Name"[[:space:]]*:[[:space:]]*"'"$package"'"' <<< "$response" \
      || die "Configured AUR package did not resolve exactly: $package"
  done
}

stage_first_boot_credentials() {
  if ! bool_true "$ENABLE_TPM" || ! bool_true "$STAGE_TPM_CREDENTIALS"; then
    unset INSTALL_LUKS_RECOVERY_CREDENTIAL INSTALL_TPM_PIN_CREDENTIAL 2>/dev/null || true
    return 0
  fi
  [[ -n ${INSTALL_LUKS_RECOVERY_CREDENTIAL:-} ]] \
    || die "The retained LUKS credential is unavailable for first-boot TPM enrollment."

  local pending="$INSTALL_ROOT/var/lib/arch-workstation/pending-credentials"
  install -d -m 0700 "$pending"
  chattr +C "$pending" 2>/dev/null || true
  printf '%s' "$INSTALL_LUKS_RECOVERY_CREDENTIAL" > "$pending/luks-passphrase"
  chmod 0600 "$pending/luks-passphrase"
  if bool_true "$TPM_WITH_PIN"; then
    [[ -n ${INSTALL_TPM_PIN_CREDENTIAL:-} ]] \
      || die "The TPM2 PIN is unavailable for first-boot enrollment."
    printf '%s' "$INSTALL_TPM_PIN_CREDENTIAL" > "$pending/tpm2-pin"
    chmod 0600 "$pending/tpm2-pin"
  fi
  cat > "$pending/README" <<'EOF_PENDING'
Temporary credentials staged inside the encrypted root filesystem by the installer.
They are removed immediately after successful TPM2 enrollment.
EOF_PENDING
  chmod 0600 "$pending/README"
  unset INSTALL_LUKS_RECOVERY_CREDENTIAL INSTALL_TPM_PIN_CREDENTIAL
}

copy_persistent_package_cache_to_target() {
  local package_cache=${ARCHWS_PACKAGE_CACHE_DIR:-} sync_cache=${ARCHWS_SYNC_CACHE_DIR:-}
  if [[ -n $package_cache && -d $package_cache ]]; then
    info "Copying the persistent official package cache into the encrypted target."
    rsync -a "$package_cache/" "$INSTALL_ROOT/var/cache/pacman/pkg/"
  fi
  if [[ -n $sync_cache && -d $sync_cache ]]; then
    mkdir -p "$INSTALL_ROOT/var/lib/pacman/sync"
    rsync -a --delete "$sync_cache/" "$INSTALL_ROOT/var/lib/pacman/sync/"
  fi
}

install_base_system() {
  info "Installing the base Arch system and a minimal graphical login."
  build_package_lists
  enable_live_iso_multilib
  if [[ ${ARCHWS_SOURCE_MODE:-live} == offline ]]; then
    local offline_file_list
    local -a offline_package_files=()
    offline_file_list=$(resolve_offline_base_package_files) \
      || die 'Failed to construct the verified offline base-package file list.'
    mapfile -t offline_package_files <<< "$offline_file_list"
    info "Installing ${#offline_package_files[@]} cached package files without repository synchronisation."
    # pacstrap's normal sync mode is -Sy even when -c uses the host cache. -U
    # is therefore required for a genuinely offline bootstrap from local files.
    pacstrap -U "$INSTALL_ROOT" "${offline_package_files[@]}"
  else
    local -a pacstrap_args=(-K)
    if bool_true "${ARCHWS_PACSTRAP_USE_HOST_CACHE:-false}"; then
      pacstrap_args+=(-c)
    fi
    pacstrap "${pacstrap_args[@]}" "$INSTALL_ROOT" "${BASE_INSTALL_PACKAGES[@]}"
  fi
  copy_persistent_package_cache_to_target
  stage_first_boot_credentials
  write_target_fstab
  copy_repository_to_target

  mkdir -p "$INSTALL_ROOT/etc/arch-installer"
  shell_quote_file "$INSTALL_ROOT/etc/arch-installer/install.env" \
    "ARCH_DISK=$DISK" \
    "ESP_PART=$ESP_PART" \
    "ROOT_PART=$ROOT_PART" \
    "LUKS_UUID=$LUKS_UUID" \
    "CRYPT_NAME=$CRYPT_NAME" \
    "KERNELS=$KERNELS" \
    "ARCH_USER=$USERNAME"
  install -m 0600 "$CONFIG_FILE" "$INSTALL_ROOT/etc/arch-installer/install.conf"
  cat >> "$INSTALL_ROOT/etc/arch-installer/install.conf" <<'EOF_RUNTIME'

# Runtime safety overrides added by the installer. Re-enable deliberately after boot.
LUKS_PASSPHRASE_FILE=""
USER_PASSWORD_FILE=""
TPM_PIN_FILE=""
NONINTERACTIVE=false
WIPE_CONFIRMATION=""
ALLOW_NON_ARCHISO=false
EOF_RUNTIME
  printf 'INITIAL_INSTALL_SOURCE_MODE=%q\n' "${ARCHWS_SOURCE_MODE:-live}" \
    >> "$INSTALL_ROOT/etc/arch-installer/install.conf"

  success "Base packages installed."
}

configure_base_system() {
  info "Configuring the target system."
  arch-chroot "$INSTALL_ROOT" /opt/arch-workstation/scripts/install/chroot-configure.sh \
    /opt/arch-workstation/config/install.conf

  [[ -n ${INSTALL_USER_PASSWORD:-} ]] || die "The user password was not collected before installation."
  printf '%s:%s\n' "$USERNAME" "$INSTALL_USER_PASSWORD" | arch-chroot "$INSTALL_ROOT" chpasswd
  unset INSTALL_USER_PASSWORD

  success "Base system configured."
}

prepare_target_secure_boot() {
  if ! bool_true "$ENABLE_SECURE_BOOT" || ! bool_true "$AUTO_PREPARE_SECURE_BOOT"; then
    return 0
  fi

  info "Enrolling Secure Boot owner keys and signing all target EFI binaries before first boot."
  arch-chroot "$INSTALL_ROOT" /usr/bin/env \
    ARCH_WORKSTATION_ROOT=/opt/arch-workstation \
    ARCH_WORKSTATION_CONFIG=/etc/arch-installer/install.conf \
    /opt/arch-workstation/scripts/security/secure-boot.sh --yes
  success "Secure Boot owner keys and signed boot assets are prepared."
}

create_efi_boot_entry() {
  info "Creating a UEFI NVRAM boot entry."
  if ! efibootmgr --create --disk "$DISK" --part 1 \
    --label 'Linux Boot Manager' \
    --loader '\EFI\systemd\systemd-bootx64.efi'; then
    warn "Could not create the NVRAM entry. The standard fallback path EFI/BOOT/BOOTX64.EFI was installed and may still boot."
  fi
}
