#!/usr/bin/env bash

write_target_fstab() {
  local root_uuid esp_uuid
  root_uuid=$(blkid -s UUID -o value "/dev/mapper/$CRYPT_NAME")
  esp_uuid=$(blkid -s UUID -o value "$ESP_PART")

  cat > "$INSTALL_ROOT/etc/fstab" <<EOF
# Generated by arch-workstation. See docs/ARCHITECTURE.md.
UUID=$root_uuid  /                       btrfs  rw,noatime,compress=zstd:1,subvol=@           0 0
UUID=$root_uuid  /home                   btrfs  rw,noatime,compress=zstd:1,subvol=@home       0 0
UUID=$root_uuid  /var/log                btrfs  rw,noatime,compress=zstd:1,subvol=@var_log    0 0
UUID=$root_uuid  /var/cache/pacman/pkg   btrfs  rw,noatime,compress=zstd:1,subvol=@pkg        0 0
UUID=$root_uuid  /.snapshots             btrfs  rw,noatime,compress=zstd:1,subvol=@snapshots  0 0
UUID=$esp_uuid   /efi                    vfat   rw,relatime,fmask=0077,dmask=0077,utf8,errors=remount-ro    0 2
EOF
}

copy_repository_to_target() {
  local target="$INSTALL_ROOT/opt/arch-workstation"
  local provenance="${MASON_REPO_COMMIT:-source-archive}"
  local git_toplevel=""
  mkdir -p "$target"

  # A Git worktree is copied from its tracked-file set. This preserves tracked
  # customisations while excluding .git internals, ignored secrets, and other
  # untracked files from the installed root-owned source snapshot.
  if command -v git >/dev/null 2>&1; then
    git_toplevel=$(git -C "$REPO_ROOT" rev-parse --show-toplevel 2>/dev/null || true)
  fi
  if [[ -z ${MASON_REPO_COMMIT:-} && -n $git_toplevel \
    && $(readlink -f "$git_toplevel") == $(readlink -f "$REPO_ROOT") ]]; then
    provenance=$(git -C "$REPO_ROOT" rev-parse HEAD)
    if ! git -C "$REPO_ROOT" diff --quiet HEAD --; then
      provenance+="-dirty"
    fi
    (
      cd "$REPO_ROOT"
      git ls-files -z | tar --null --files-from=- --create --file=-
    ) | tar -C "$target" -xf -
  else
    tar -C "$REPO_ROOT" \
      --exclude='.git' \
      --exclude='config/install.conf' \
      --exclude='config/usb.conf' \
      --exclude='config/secrets.conf' \
      --exclude='config/secrets.env' \
      --exclude='*.secret' \
      --exclude='*.key' \
      --exclude='*.pem' \
      --exclude='.cache' \
      --exclude='.usb-build' \
      --exclude='build' \
      --exclude='dist' \
      --exclude='.idea' \
      --exclude='.vscode' \
      --exclude='*.img' \
      --exclude='*.iso' \
      --exclude='*.log' \
      --exclude='*.zip' \
      --exclude='*.tar.gz' \
      -cf - . | tar -C "$target" -xf -
  fi
  printf '%s\n' "$provenance" > "$target/BUILD_COMMIT"

  install -Dm0644 "$CONFIG_FILE" "$target/config/install.conf"
  chmod +x "$target/install.sh" "$target/archctl" 2>/dev/null || true
  find "$target/scripts" -type f -name '*.sh' -exec chmod 0755 {} +
}

install_base_system() {
  info "Installing the complete configured Arch workstation package set."

  local -a packages
  local -a pacstrap_args=(-K)
  if [[ ${INSTALL_SOURCE_RESOLVED:-online} == offline ]]; then
    collect_all_requested_packages packages
    pacstrap_args+=(-C "$OFFLINE_PACMAN_CONFIG")
  else
    collect_official_packages packages
  fi

  pacstrap "${pacstrap_args[@]}" "$INSTALL_ROOT" "${packages[@]}"
  write_target_fstab
  copy_repository_to_target

  mkdir -p "$INSTALL_ROOT/etc/arch-installer"
  shell_quote_file "$INSTALL_ROOT/etc/arch-installer/install.env" \
    "ARCH_DISK=$DISK" \
    "ESP_PART=$ESP_PART" \
    "ROOT_PART=$ROOT_PART" \
    "LUKS_UUID=$LUKS_UUID" \
    "CRYPT_NAME=$CRYPT_NAME" \
    "KERNELS=$KERNELS" \
    "ARCH_USER=$USERNAME" \
    "INSTALL_SOURCE_AT_INSTALL=${INSTALL_SOURCE_RESOLVED:-online}"
  printf '%s\n' "${INSTALL_SOURCE_RESOLVED:-online}" \
    > "$INSTALL_ROOT/etc/arch-installer/install-source"
  printf '%s\n' true > "$INSTALL_ROOT/etc/arch-installer/official-packages-preinstalled"
  if [[ ${INSTALL_SOURCE_RESOLVED:-online} == offline ]] && bool_true "$ENABLE_AUR"; then
    printf '%s\n' true > "$INSTALL_ROOT/etc/arch-installer/aur-packages-preinstalled"
  fi

  install -m 0600 "$CONFIG_FILE" "$INSTALL_ROOT/etc/arch-installer/install.conf"
  cat >> "$INSTALL_ROOT/etc/arch-installer/install.conf" <<'EOF_CONFIG'

# Runtime safety overrides added by the installer. Re-enable deliberately after boot.
LUKS_PASSPHRASE_FILE=""
USER_PASSWORD_FILE=""
NONINTERACTIVE=false
WIPE_CONFIRMATION=""
SECURE_BOOT_CONFIRMATION=""
ALLOW_NON_ARCHISO=false
# USB paths are live-environment paths and must not persist as policy.
INSTALL_SOURCE_MODE="auto"
OFFLINE_REPO_PATH=""
OFFLINE_AUR_REPO_PATH=""
EOF_CONFIG

  success "Configured packages installed from ${INSTALL_SOURCE_RESOLVED:-online}."
}

configure_base_system() {
  info "Configuring the target system."
  arch-chroot "$INSTALL_ROOT" /opt/arch-workstation/scripts/install/chroot-configure.sh \
    /opt/arch-workstation/config/install.conf

  [[ -n ${INSTALL_USER_PASSWORD:-} ]] || die "The user password was not collected before installation."
  printf '%s:%s\n' "$USERNAME" "$INSTALL_USER_PASSWORD" | arch-chroot "$INSTALL_ROOT" chpasswd
  unset INSTALL_USER_PASSWORD

  success "Base system configured."
}

create_efi_boot_entry() {
  info "Creating a UEFI NVRAM boot entry."
  if ! efibootmgr --create --disk "$DISK" --part 1 \
    --label 'Linux Boot Manager' \
    --loader '\EFI\systemd\systemd-bootx64.efi'; then
    warn "Could not create the NVRAM entry. The standard fallback path EFI/BOOT/BOOTX64.EFI was installed and may still boot."
  fi
}
