#!/usr/bin/env bash

write_target_fstab() {
  local root_uuid esp_uuid
  root_uuid=$(blkid -s UUID -o value "/dev/mapper/$CRYPT_NAME")
  esp_uuid=$(blkid -s UUID -o value "$ESP_PART")

  cat > "$INSTALL_ROOT/etc/fstab" <<EOF_FSTAB
# Generated by arch-workstation. See docs/ARCHITECTURE.md.
UUID=$root_uuid  /                       btrfs  rw,noatime,compress=zstd:1,subvol=@           0 0
UUID=$root_uuid  /home                   btrfs  rw,noatime,compress=zstd:1,subvol=@home       0 0
UUID=$root_uuid  /var/log                btrfs  rw,noatime,compress=zstd:1,subvol=@var_log    0 0
UUID=$root_uuid  /var/cache/pacman/pkg   btrfs  rw,noatime,compress=zstd:1,subvol=@pkg        0 0
UUID=$root_uuid  /.snapshots             btrfs  rw,noatime,compress=zstd:1,subvol=@snapshots  0 0
UUID=$esp_uuid   /efi                    vfat   rw,relatime,fmask=0077,dmask=0077,utf8,errors=remount-ro    0 2
EOF_FSTAB
}

copy_repository_to_target() {
  local target="$INSTALL_ROOT/opt/arch-workstation"
  local provenance="source-archive"
  local git_toplevel=""
  mkdir -p "$target"

  # A Git worktree is copied from its tracked-file set. This preserves tracked
  # customisations while excluding .git internals, ignored secrets, and other
  # untracked files from the installed root-owned source snapshot.
  if command -v git >/dev/null 2>&1; then
    git_toplevel=$(git -C "$REPO_ROOT" rev-parse --show-toplevel 2>/dev/null || true)
  fi
  if [[ -n $git_toplevel && $(readlink -f "$git_toplevel") == $(readlink -f "$REPO_ROOT") ]]; then
    provenance=$(git -C "$REPO_ROOT" rev-parse HEAD)
    if ! git -C "$REPO_ROOT" diff --quiet HEAD --; then
      provenance+="-dirty"
    fi
    (
      cd "$REPO_ROOT" || exit 1
      git ls-files -z | tar --null --files-from=- --create --file=-
    ) | tar -C "$target" -xf -
  else
    tar -C "$REPO_ROOT" \
      --exclude='.git' \
      --exclude='config/install.conf' \
      --exclude='config/secrets.conf' \
      --exclude='config/secrets.env' \
      --exclude='*.secret' \
      --exclude='*.key' \
      --exclude='*.pem' \
      --exclude='*.zip' \
      --exclude='*.tar.gz' \
      -cf - . | tar -C "$target" -xf -
  fi
  printf '%s\n' "$provenance" > "$target/BUILD_COMMIT"

  install -Dm0644 "$CONFIG_FILE" "$target/config/install.conf"
  chmod 0755 "$target/install.sh" "$target/start.sh" "$target/archctl" "$target/upgrade-existing.sh"
  find "$target/scripts" -type f -name '*.sh' -exec chmod 0755 {} +
}

enable_live_iso_multilib() {
  if ! bool_true "$ENABLE_MULTILIB"; then
    return 0
  fi

  info "Enabling multilib in the live ISO before package resolution."
  if ! pacman-conf --repo-list 2>/dev/null | grep -qx multilib; then
    local temp_conf
    temp_conf=$(mktemp)
    awk '
      /^#?\[multilib\]$/ {
        print "[multilib]"
        in_multilib = 1
        found_multilib = 1
        next
      }
      in_multilib && /^#?Include[[:space:]]*=[[:space:]]*\/etc\/pacman\.d\/mirrorlist$/ {
        sub(/^#/, "")
        print
        next
      }
      in_multilib && /^\[/ { in_multilib = 0 }
      { print }
      END {
        if (!found_multilib) {
          print ""
          print "[multilib]"
          print "Include = /etc/pacman.d/mirrorlist"
        }
      }
    ' /etc/pacman.conf > "$temp_conf"
    install -m 0644 "$temp_conf" /etc/pacman.conf
    rm -f "$temp_conf"
  fi

  pacman-conf --repo-list | grep -qx multilib \
    || die "Could not enable the multilib repository in the live ISO."
  pacman -Sy --noconfirm
  pacman -Slq multilib >/dev/null 2>&1 \
    || die "The multilib repository database is unavailable in the live ISO."
}

build_package_lists() {
  local -a kernels cpu_packages gpu_packages
  read -r -a kernels <<< "$KERNELS"

  case "$CPU_VENDOR" in
    intel) cpu_packages=(intel-ucode sof-firmware) ;;
    amd) cpu_packages=(amd-ucode) ;;
  esac

  case "$GPU_VENDOR" in
    intel) gpu_packages=(mesa vulkan-intel intel-media-driver) ;;
    amd) gpu_packages=(mesa vulkan-radeon libva-mesa-driver) ;;
    generic) gpu_packages=(mesa) ;;
  esac

  BASE_INSTALL_PACKAGES=(
    base base-devel "${kernels[@]}" linux-firmware wireless-regdb "${cpu_packages[@]}"
    btrfs-progs cryptsetup dosfstools gptfdisk efibootmgr
    mkinitcpio systemd-ukify sbsigntools sbctl tpm2-tools tpm2-tss
    networkmanager wpa_supplicant openssh
    sudo git vim curl rsync tar ansible-core python
    man-db man-pages texinfo bash-completion
    zram-generator
    xorg-server xorg-xinit xf86-input-libinput "${gpu_packages[@]}"
    xfce4-session xfce4-panel xfdesktop xfwm4 xfce4-settings xfce4-appfinder
    xfce4-terminal xfce4-power-manager xfce4-notifyd xfce4-screensaver
    xfce4-pulseaudio-plugin thunar thunar-volman tumbler
    lightdm lightdm-gtk-greeter
    pipewire pipewire-alsa pipewire-pulse wireplumber pavucontrol
    bluez bluez-utils
    gnome-keyring polkit-gnome
    gvfs gvfs-mtp udisks2 network-manager-applet
    xdg-user-dirs xdg-utils xdg-desktop-portal-gtk
    noto-fonts noto-fonts-emoji ttf-dejavu
  )

  REQUIRED_OFFICIAL_PACKAGES=(
    "${BASE_INSTALL_PACKAGES[@]}"
    bat btop fd fastfetch fzf jq less pacman-contrib ripgrep unzip wget zip
    file-roller mousepad ristretto xdg-desktop-portal
    cmake dotnet-sdk ninja shellcheck
  )

  if bool_true "$ENABLE_DOCKER"; then
    REQUIRED_OFFICIAL_PACKAGES+=(docker docker-buildx docker-compose)
  fi
  if bool_true "$ENABLE_GAMING"; then
    REQUIRED_OFFICIAL_PACKAGES+=(
      steam gamemode lib32-gamemode lib32-libpulse lib32-mesa mangohud vulkan-tools
    )
    case "$GPU_VENDOR" in
      intel) REQUIRED_OFFICIAL_PACKAGES+=(vulkan-intel lib32-vulkan-intel) ;;
      amd) REQUIRED_OFFICIAL_PACKAGES+=(vulkan-radeon lib32-vulkan-radeon) ;;
    esac
  fi
  if bool_true "$ENABLE_SNAPSHOTS"; then
    REQUIRED_OFFICIAL_PACKAGES+=(snapper snap-pac)
  fi
  if bool_true "$ENABLE_T480"; then
    REQUIRED_OFFICIAL_PACKAGES+=(bolt ethtool fwupd smartmontools thermald tlp tlp-rdw)
  fi

  mapfile -t REQUIRED_OFFICIAL_PACKAGES < <(printf '%s\n' "${REQUIRED_OFFICIAL_PACKAGES[@]}" | sort -u)
}

verify_live_package_resolution() {
  build_package_lists
  info "Resolving every configured official package before touching the target disk."
  pacman -Sp --noconfirm --print-format '%n' "${REQUIRED_OFFICIAL_PACKAGES[@]}" >/dev/null \
    || die "One or more required official packages cannot be resolved. Check mirrors and repository configuration."
}

verify_aur_package_resolution() {
  bool_true "$ENABLE_AUR" || return 0

  local -a packages curl_args
  local package response
  read -r -a packages <<< "$AUR_PACKAGES"
  packages=("$AUR_HELPER_PACKAGE" "${packages[@]}")
  curl_args=(--fail --silent --show-error --retry 3 --get)
  for package in "${packages[@]}"; do
    curl_args+=(--data-urlencode "arg[]=$package")
  done

  info "Resolving the configured AUR allow-list before touching the target disk."
  response=$(curl "${curl_args[@]}" https://aur.archlinux.org/rpc/v5/info) \
    || die "Could not query AUR package metadata."
  for package in "${packages[@]}"; do
    grep -Eq '"Name"[[:space:]]*:[[:space:]]*"'"$package"'"' <<< "$response" \
      || die "Configured AUR package did not resolve exactly: $package"
  done
}

install_base_system() {
  info "Installing the base Arch system and a minimal graphical login."
  build_package_lists
  enable_live_iso_multilib
  pacstrap -K "$INSTALL_ROOT" "${BASE_INSTALL_PACKAGES[@]}"
  write_target_fstab
  copy_repository_to_target

  mkdir -p "$INSTALL_ROOT/etc/arch-installer"
  shell_quote_file "$INSTALL_ROOT/etc/arch-installer/install.env" \
    "ARCH_DISK=$DISK" \
    "ESP_PART=$ESP_PART" \
    "ROOT_PART=$ROOT_PART" \
    "LUKS_UUID=$LUKS_UUID" \
    "CRYPT_NAME=$CRYPT_NAME" \
    "KERNELS=$KERNELS" \
    "ARCH_USER=$USERNAME"
  install -m 0600 "$CONFIG_FILE" "$INSTALL_ROOT/etc/arch-installer/install.conf"
  cat >> "$INSTALL_ROOT/etc/arch-installer/install.conf" <<'EOF_RUNTIME'

# Runtime safety overrides added by the installer. Re-enable deliberately after boot.
LUKS_PASSPHRASE_FILE=""
USER_PASSWORD_FILE=""
NONINTERACTIVE=false
WIPE_CONFIRMATION=""
ALLOW_NON_ARCHISO=false
EOF_RUNTIME

  success "Base packages installed."
}

configure_base_system() {
  info "Configuring the target system."
  arch-chroot "$INSTALL_ROOT" /opt/arch-workstation/scripts/install/chroot-configure.sh \
    /opt/arch-workstation/config/install.conf

  [[ -n ${INSTALL_USER_PASSWORD:-} ]] || die "The user password was not collected before installation."
  printf '%s:%s\n' "$USERNAME" "$INSTALL_USER_PASSWORD" | arch-chroot "$INSTALL_ROOT" chpasswd
  unset INSTALL_USER_PASSWORD

  success "Base system configured."
}

prepare_target_secure_boot() {
  if ! bool_true "$ENABLE_SECURE_BOOT" || ! bool_true "$AUTO_PREPARE_SECURE_BOOT"; then
    return 0
  fi

  info "Enrolling Secure Boot owner keys and signing all target EFI binaries before first boot."
  arch-chroot "$INSTALL_ROOT" /usr/bin/env \
    ARCH_WORKSTATION_ROOT=/opt/arch-workstation \
    ARCH_WORKSTATION_CONFIG=/etc/arch-installer/install.conf \
    /opt/arch-workstation/scripts/security/secure-boot.sh --yes
  success "Secure Boot owner keys and signed boot assets are prepared."
}

create_efi_boot_entry() {
  info "Creating a UEFI NVRAM boot entry."
  if ! efibootmgr --create --disk "$DISK" --part 1 \
    --label 'Linux Boot Manager' \
    --loader '\EFI\systemd\systemd-bootx64.efi'; then
    warn "Could not create the NVRAM entry. The standard fallback path EFI/BOOT/BOOTX64.EFI was installed and may still boot."
  fi
}
